.Dd December 13, 2023
.Dt kitserv_api_reset_headers 3
.Nm kitserv_api_reset_headers(3)
.Sh SYNOPSIS
.Pp
.Lb kitserv
.Pp
.In kitserv.h
.Pp
.Ft void
.Fn kitserv_api_reset_headers "struct kitserv_client*"
.Sh DESCRIPTION
The
.Sy kitserv_api_reset_headers()
function clears the headers of a response.
.Sh COPYRIGHT
.Pp
Copyright (c) 2023 Jmcgee1125.
.Pp
Kitserv is licensed under the GNU Affero GPL v3. You are free to redistribute
and modify this code as you see fit, provided that you make the source code
freely available under these terms.
