.Dd December 11, 2023
.Dt kitserv_api_get_request_query 3
.Nm kitserv_api_get_request_query(3)
.Sh SYNOPSIS
.Pp
.Lb kitserv
.Pp
.In kitserv.h
.Pp
.Ft const char*
.Fn kitserv_api_get_request_query "struct kitserv_client*"
.Sh DESCRIPTION
The
.Sy kitserv_api_get_request_query()
function returns a pointer to a null-terminated string for the client's
request query. If the client did not put a query in the request, this
function will return NULL.
.Pp
The query string returned is unparsed, but the leading ? is removed. So, this
function returns (on success) a pointer to an &-delimited list of the query's
key-value pairs.
.Sh RETURN VALUE
A pointer to the client's query, or NULL if not found.
.Sh COPYRIGHT
.Pp
Copyright (c) 2023 Jmcgee1125.
.Pp
Kitserv is licensed under the GNU Affero GPL v3. You are free to redistribute
and modify this code as you see fit, provided that you make the source code
freely available under these terms.
