.Dd December 8, 2023
.Dt kitserv_server_start 3
.Nm kitserv_server_start(3)
.Sh SYNOPSIS
.Pp
.Lb kitserv
.Pp
.In kitserv.h
.Pp
struct kitserv_config {
.in +0n
    char* port_string;
    int num_workers;
    int num_slots;
    bool bind_ipv4;
    bool bind_ipv6;
    bool silent_mode;
    struct kitserv_request_context* http_root_context;
    struct kitserv_api_tree* api_tree;
.in -0n
};
.Pp
struct kitserv_request_context {
.in +0n
    char* root;
    char* root_fallback;
    char* fallback;
    bool use_http_append_fallback;
.in -0n
};
.Pp
struct kitserv_api_entry {
.in +0n
    char* prefix;
    int prefix_length;
    enum kitserv_http_method method;
    kitserv_api_handler_t handler;
    bool finishes_path;
.in -0n
};
.Pp
struct kitserv_api_tree {
.in +0n
    char* prefix;
    int prefix_length;
    struct kitserv_api_tree* subtrees;
    struct kitserv_api_entry* entries;
    int num_subtrees;
    int num_entries;
.in -0n
};
.Pp
.Ft void
.Fn kitserv_server_start "struct kitserv_config*"
.Sh DESCRIPTION
.Pp
The
.Sy kitserv_server_start()
function initializes and starts an instance of the Kitserv web server.
.Pp
.Em struct kitserv_config
contains the configuration for this instance. The entries of that struct
are defined as follows:
.in +4n
.Bl -tag -width Ds
.It Em char* port_string
Port to run on, as a string (e.g. "8012").
.It Em int num_workers
Number of worker threads to use.
.It Em int num_slots
Number of connection slots to use. Kitserv preallocates these slots,
this is a hard limit.
.It Em bool bind_ipv4
Bind IPv4 only.
.It Em bool bind_ipv6
Bind IPv6, using dual binding if enabled. IPv6 binding happens before
IPv4 binding.
.It Em bool silent_mode
Disable non-catastrophic error prints and logging. Not all printouts are
removed, only logging and most recoverable errors.
.It Em struct kitserv_request_context* http_root_context;
Default web context to serve from.
.It Em struct kitserv_api_tree* api_tree
API endpoint tree to serve API requests into. Use NULL for this field
to disable the API entirely.
.in -4n
.El
.Pp
.Em struct kitserv_request_context
Defines a static file server context. This includes the main web
directory and fallback handling. The entries of that struct are
defined as follows:
.in +4n
.Bl -tag -width Ds
.It Em char* root
Root directory to serve files from.
.It Em char* root_fallback
Fallback resource to serve when the request path is /. This location
is relative to the main root. Example: "/index.html"
.It Em char* fallback
Fallback resource to serve when the request path does not exist. This
location is relative to the main root. Example: "/200.html"
.It Em bool use_http_append_fallback
Retry request with .html appended if the original path does not
exist. Example: "/public" -> "/public.html"
.in -4n
.El
.Pp
.Em struct kitserv_api_tree
defines API trees and subtrees for parsing.
.Em struct kitserv_api_entry
defines an API endpoint. When a request arrives, Kitserv splits the path
on / characters and iterates the tree. Each subtree or entry contains a
.Em prefix
field which is compared against the current path element. If an entry's
prefix and HTTP request method matches, the API handler function is
called. The handler function takes a
.Em data
argument, which can be preserved across calls (if set by the handler).
.Pp
The fields of
.Em struct kitserv_api_tree
are defined as follows:
.in +4n
.Bl -tag -width Ds
.It Em char* prefix
Prefix of this subtree. Includes no / characters. The API tree root has
no prefix, it is always iterated.
.It Em int prefix_length
Length of this subtree's prefix.
.It Em struct kitserv_api_tree* subtrees
Array of subtrees for this tree.
.It Em struct kitserv_api_entry* entries
Array of API endpoints for this tree.
.It Em int num_subtrees
Number of subtrees in array.
.It Em int num_entries
Number of endpoints in array.
.El
.in -4n
.Pp
The fields of
.Em struct kitserv_api_entry
are defined as follows:
.in +4n
.Bl -tag -width Ds
.It Em char* prefix
Prefix of this subtree. Includes no / characters.
.It Em int prefix_length
Length of this subtree's prefix.
.It Em enum kitserv_http_method method
HTTP method accepted by this endpoint.
.Em HTTP_GET
and
.Em HTTP_HEAD
are both serviced by endpoints declared as
.Em HTTP_GET
do not use
.Em HTTP_HEAD
directly here.
.It Em kitserv_api_handler_t handler
Handler function to do API parsing. This function will be repeatedly called
until the response status is set.
.It Em bool finishes_path
If true, do not allow any additional path elements. For example,
"/api/login/extra" will not be entered for "/api/login" if this is true. (Note
that the entry itself would actually have the prefix "login", with its parent
tree having "api").
.El
.in -4n
.Sh COPYRIGHT
.Pp
Copyright (c) 2023 Jmcgee1125.
.Pp
Kitserv is licensed under the GNU Affero GPL v3. You are free to redistribute
and modify this code as you see fit, provided that you make the source code
freely available under these terms.
