.Dd December 11, 2023
.Dt http_handle_static_path 3
.Nm http_handle_static_path(3)
.Sh SYNOPSIS
.Pp
.Lb kitserv
.Pp
.In kitserv.h
.Pp
.Ft int
.Fn http_handle_static_path "struct kitserv_client*" "const char* path" "struct kitserv_request_context* ctx"
.Sh DESCRIPTION
The
.Sy http_handle_static_path()
function serves a static file using the given path and context.
It is recommended to finish API handling after calling this function, as the
response will be fully set up.
.Pp
The path is served relative to the root directory of the context struct. The
context may define fallback resources to be searched if the original path
does not work. These paths are also relative to the context root.
.Pp
NULL may be passed as the context. In this case, Kitserv will use the default
context that was passed during server startup. This can be useful for
implementing authentication, as the request can be redirected through the API
for authentication before returning to a standard Kitserv response.
.Pp
.Sh RETURN VALUE
On success, this function returns 0. On failure, this function returns -1,
setting errno and a corresponding HTTP response status.
.Sh ERRORS
This function shall fail if:
.Bl -tag -width Ds
.It Sy HTTP 403 / EACCES
The path was found, but the server did not have permissions to open it.
.It Sy HTTP 405 / ENOTSUP
The request method was not GET or HEAD.
.It Sy HTTP 414 / ENAMETOOLONG
The total path length generated was too long.
.It Sy HTTP 500 / ENOMEM
There was not enough space to store the headers for this response.
Sets HTTP 500, as this is unexpected.
.El
.Pp
This function may also fail for any reason that
.Sy open(2)
may fail. In this case, HTTP 500 will be set.
.Sh COPYRIGHT
.Pp
Copyright (c) 2023 Jmcgee1125.
.Pp
Kitserv is licensed under the GNU Affero GPL v3. You are free to redistribute
and modify this code as you see fit, provided that you make the source code
freely available under these terms.
