.Dd December 11, 2023
.Dt kitserv_api_set_preserve_body_on_error 3
.Nm kitserv_api_set_preserve_body_on_error(3)
.Sh SYNOPSIS
.Pp
.Lb kitserv
.Pp
.In kitserv.h
.Pp
.Ft void
.Fn kitserv_api_set_preserve_body_on_error "struct kitserv_client*" "bool preserve_enabled"
.Sh DESCRIPTION
The
.Sy kitserv_api_set_preserve_body_on_error()
function instructs Kitserv to not discard the body or headers when returning an
error response to the client.
.Pp
For more information, see
.Sy kitserv_api_set_preseve_headers_on_error() . No
.Sh COPYRIGHT
.Pp
Copyright (c) 2023 Jmcgee1125.
.Pp
Kitserv is licensed under the GNU Affero GPL v3. You are free to redistribute
and modify this code as you see fit, provided that you make the source code
freely available under these terms.
