.Dd December 11, 2023
.Dt kitserv_api_get_request_disposition 3
.Nm kitserv_api_get_request_disposition(3)
.Sh SYNOPSIS
.Pp
.Lb kitserv
.Pp
.In kitserv.h
.Pp
.Ft const char*
.Fn kitserv_api_get_request_disposition "struct kitserv_client*"
.Sh DESCRIPTION
The
.Sy kitserv_api_get_request_disposition()
function returns a pointer to a null-terminated string for the client's
value in the content-disposition header.
.Sh COPYRIGHT
.Pp
Copyright (c) 2023 Jmcgee1125.
.Pp
Kitserv is licensed under the GNU Affero GPL v3. You are free to redistribute
and modify this code as you see fit, provided that you make the source code
freely available under these terms.
