.Dd December 21, 2023
.Os LOCAL
.Dt KITSERV_API_SET_SEND_RANGE 3 LOCAL
.Sh NAME
.Nm kitserv_api_set_send_range
.Nd set the response range to send from
.Sh LIBRARY
.Lb kitserv
.Sh SYNOPSIS
.In kitserv.h
.Ft int
.Fo kitserv_api_set_send_range
.Fa "struct kitserv_client*"
.Fa "off_t from"
.Fa "off_t to"
.Fc
.Sh DESCRIPTION
The
.Fn kitserv_api_set_send_range
function sets the range to send the response from, byte-inclusive.
.Pp
Note that
.Fa to
is ignored when sending a request from a body (not a file). Kitserv will
always send until the end of the buffer.
.Pp
It is the endpoint's responsibility to ensure that
.Fa to
does not exceed the length of the file being sent.
.Pp
This function does not set the content-range header on the response. Use
.Xr kitserv_http_header_add 3 . No
.Sh RETURN VALUE
On success, this function returns 0. On failure, this function returns -1,
setting
.Va errno . No
.Sh ERRORS
These functions shall fail if:
.Bl -tag -width Ds
.It Sy EINVAL
Either
.Fa from
or
.Fa to
is negative.
.El
.Sh SEE ALSO
.Xr kitserv 3 ,
.Xr kitserv_api_send_file 3 ,
.Xr kitserv_http_header_add 3
.Sh COPYRIGHT
Copyright (c) 2023 Jmcgee1125.
.Pp
Kitserv is licensed under the GNU Affero GPL v3. You are free to redistribute
and modify this code as you see fit, provided that you make the source code
freely available under these terms.
