.Dd December 21, 2023
.Os LOCAL
.Dt KITSERV_API_GET_REQUEST_QUERY 3 LOCAL
.Sh NAME
.Nm kitserv_api_get_request_query
.Nd get request's query string
.Sh LIBRARY
.Lb libkitserv
.Sh SYNOPSIS
.In kitserv.h
.Ft const char*
.Fn kitserv_api_get_request_query "struct kitserv_client*"
.Sh DESCRIPTION
The
.Fn kitserv_api_get_request_query
function returns a pointer to a null-terminated string for the client's
request query. If the client did not put a query in the request, this
function will return
.Dv NULL . No \&
.Pp
The query string returned is unparsed, but the leading ? is removed. So, this
function returns (on success) a pointer to an &-delimited string of the
query's key-value pairs.
.Sh RETURN VALUE
A pointer to the client's query, or
.Dv NULL No if not found.
.Sh SEE ALSO
.Xr kitserv 3 ,
.Xr kitserv_api_get_request_content_length 3 , 
.Xr kitserv_api_get_request_cookie 3 ,
.Xr kitserv_api_get_request_disposition 3 ,
.Xr kitserv_api_get_request_method 3 , 
.Xr kitserv_api_get_request_mime_type 3 , 
.Xr kitserv_api_get_request_modified_since_difference 3 , 
.Xr kitserv_api_get_request_path 3 , 
.Xr kitserv_api_get_request_range 3
.Sh COPYRIGHT
Copyright (c) 2023 Jmcgee1125.
.Pp
Kitserv is licensed under the GNU Affero GPL v3. You are free to redistribute
and modify this code as you see fit, provided that you make the source code
freely available under these terms.
